
package caiseeglise.EntreForm;

//imporation des classe

import caiseeglise.Models.Eglise;
import caiseeglise.Models.Entre;
import caiseeglise.Models.Methodes;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import java.util.Map;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

import caiseeglise.Style;

public class EntreAjoute extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EntreAjoute.class.getName());

    /**
     * Creates new form SortieAjoute
     */
    public EntreAjoute() {
        initComponents();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
          
          
          
          //appele de la focntio style
           Style style = new Style();
           
          
           style.styliserBoutonPrimary(btnajoute);
           style.styliserBoutonSuccess(jButton2);
          style.styliserTextField(txtideglise);
              style.styliserTextField(txtmontantEntre);
                  style.styliserTextField(txtmotif);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtideglise = new javax.swing.JTextField();
        txtmotif = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtmontantEntre = new javax.swing.JTextField();
        btnajoute = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ajoute une sortie");

        jLabel2.setText("id Eglise");

        jLabel3.setText("Motif");

        jLabel4.setText("Montant Entre");

        btnajoute.setText("Ajouter");
        btnajoute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnajouteActionPerformed(evt);
            }
        });

        jButton2.setText("Annuler");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel1)
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtmotif)
                    .addComponent(txtmontantEntre, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(txtideglise))
                .addGap(12, 12, 12))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnajoute)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtideglise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmotif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtmontantEntre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnajoute)
                    .addComponent(jButton2))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         // TODO add your handling code here:
         this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnajouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajouteActionPerformed
        // TODO add your handling code here:
         try {
        String ideglise = txtideglise.getText().trim();
        String motif = txtmotif.getText().trim();
        String montantStr = txtmontantEntre.getText().trim();

        if (ideglise.isEmpty() || motif.isEmpty() || montantStr.isEmpty()) {
            Methodes.showError("Tous les champs doivent être remplis.");
            return;
        }

        int montantEntre = Integer.parseInt(montantStr);
        String dateEntre = java.time.LocalDate.now().toString();

        Connection conn = Methodes.getconnexion();
        if (conn == null) return;

        conn.setAutoCommit(false);
        try {
            Entre entreModel = new Entre(conn);
            Eglise egliseModel = new Eglise(conn);

            String insertResult = entreModel.insertEntre(motif, montantEntre, dateEntre, ideglise);
            if (!"INSERT_OK".equals(insertResult)) {
                conn.rollback();
                Methodes.showError(insertResult);
                return;
            }

            String updateResult = egliseModel.mettreAJourSolde(ideglise, montantEntre);
            if (!"UPDATE_OK".equals(updateResult)) {
                conn.rollback();
                Methodes.showError(updateResult);
                return;
            }

            conn.commit();
            Methodes.showSuccess("Entrée ajoutée et solde mis à jour avec succès.");
            
             
        } catch (Exception ex) {
            conn.rollback();
            Methodes.showError("Erreur lors de la transaction : " + ex.getMessage());
        } finally {
            conn.setAutoCommit(true);
            conn.close();
        }
    } catch (NumberFormatException e) {
        Methodes.showError("Montant invalide. Veuillez entrer un nombre.");
    } catch (Exception e) {
        Methodes.showError("Erreur : " + e.getMessage());
    }
        
        
    }//GEN-LAST:event_btnajouteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EntreAjoute().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnajoute;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtideglise;
    private javax.swing.JTextField txtmontantEntre;
    private javax.swing.JTextField txtmotif;
    // End of variables declaration//GEN-END:variables
}
