
package caiseeglise;

//importation des clasee
import caiseeglise.EgliseForm.EgliseAjoute;
import caiseeglise.EntreForm.EntreAjoute;
import caiseeglise.Models.Eglise;
import caiseeglise.Models.Entre;
import caiseeglise.Models.Methodes;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import java.util.Map;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

import caiseeglise.EntreForm.EntreAjoute;



public class EntreView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EntreView.class.getName());

    /**
     * Creates new form EntreView
     */
    public EntreView() {
        initComponents();
        //appel de la fonction 
        AfficheEntre();
        
        
        
        //classe eglise
        Style style = new Style();
        style.appliquerStyleTableau(tableEntres);
        style.appliquerStyleH1(label1);
        style.styliserBoutonPrimary(jButton1);
        
        
    }
 public JPanel getPannelAjouteEntre() {
        return this.PannelAjouteEntre;
    }
    //fonction affichage
    
    
    
    
    
    
    public void AfficheEntre() {
    try {
        Connection conn = Methodes.getconnexion();
        if (conn == null) return;

        Entre entre = new Entre(conn);
        List<Map<String, Object>> data = entre.afficheEntres();

        Map<String, String> titres = Map.of(
            "identre", "ID",
            "motif", "Motif",
            "montantEntre", "Montant",
            "dateEntre", "Date",
            "ideglise", "ID Église"
        );

        DefaultTableModel model = Methodes.createTableModel(data, titres);
        tableEntres.setModel(model); // ton JTable

    } catch (SQLException e) {
        Methodes.show("Erreur lors de l'affichage : " + e.getMessage());
    }
}

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        PannelAjouteEntre = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableEntres = new javax.swing.JTable();
        label1 = new java.awt.Label();
        btnrecherche = new javax.swing.JButton();
        txtrecherche = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        date_debut = new com.toedter.calendar.JDateChooser();
        date_fin = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnmovcaisseentre = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Ajoute");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tableEntres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tableEntres);

        label1.setText("PAGE ENTRE");

        btnrecherche.setText("Recherche");
        btnrecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrechercheActionPerformed(evt);
            }
        });

        jLabel1.setText("Mouvement de caisse entre deux dates");

        jLabel2.setText("Debut");

        jLabel3.setText("Fin");

        btnmovcaisseentre.setText("mouvement de caisse");
        btnmovcaisseentre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmovcaisseentreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PannelAjouteEntreLayout = new javax.swing.GroupLayout(PannelAjouteEntre);
        PannelAjouteEntre.setLayout(PannelAjouteEntreLayout);
        PannelAjouteEntreLayout.setHorizontalGroup(
            PannelAjouteEntreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PannelAjouteEntreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PannelAjouteEntreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PannelAjouteEntreLayout.createSequentialGroup()
                        .addGroup(PannelAjouteEntreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(PannelAjouteEntreLayout.createSequentialGroup()
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(119, 119, 119)
                                .addGroup(PannelAjouteEntreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PannelAjouteEntreLayout.createSequentialGroup()
                                        .addGroup(PannelAjouteEntreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(68, 68, 68)
                                        .addGroup(PannelAjouteEntreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(date_debut, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(date_fin, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel1))
                                .addGap(260, 260, 260)
                                .addComponent(txtrecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btnrecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PannelAjouteEntreLayout.createSequentialGroup()
                                .addGap(580, 580, 580)
                                .addComponent(btnmovcaisseentre, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PannelAjouteEntreLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(187, 187, 187))))
        );
        PannelAjouteEntreLayout.setVerticalGroup(
            PannelAjouteEntreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PannelAjouteEntreLayout.createSequentialGroup()
                .addGroup(PannelAjouteEntreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PannelAjouteEntreLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(PannelAjouteEntreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtrecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnrecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PannelAjouteEntreLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(PannelAjouteEntreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(date_debut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(PannelAjouteEntreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PannelAjouteEntreLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btnmovcaisseentre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PannelAjouteEntreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGroup(PannelAjouteEntreLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(date_fin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(229, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(PannelAjouteEntre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(PannelAjouteEntre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(326, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        EntreAjoute entreajoute = new EntreAjoute();
        entreajoute.setLocationRelativeTo(null);
        entreajoute.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnrechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrechercheActionPerformed
        // TODO add your handling code here:
          String motif = txtrecherche.getText().trim(); // Récupère le texte entré

    if (motif.isEmpty()) {
        Methodes.showInfo("Veuillez entrer un motif à rechercher.");
        return;
    }

    try {
        Connection conn = Methodes.getconnexion();
        if (conn == null) return;

        Entre entre = new Entre(conn);
        List<Map<String, Object>> data = entre.rechercherParMotif(motif);

        if (data.isEmpty()) {
            Methodes.showInfo("Aucun résultat trouvé pour le motif : " + motif);
            return;
        }

        // Titres pour affichage dans le tableau
        Map<String, String> titres = Map.of(
            "identre", "ID",
            "motif", "Motif",
            "montantEntre", "Montant",
            "dateEntre", "Date",
            "ideglise", "ID Église"
        );

        DefaultTableModel model = Methodes.createTableModel(data, titres);
        tableEntres.setModel(model); // Assure-toi que TableEntre est bien déclaré

    } catch (SQLException e) {
        Methodes.showError("Erreur lors de la recherche : " + e.getMessage());
    }
        
    }//GEN-LAST:event_btnrechercheActionPerformed

    private void btnmovcaisseentreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmovcaisseentreActionPerformed
        // TODO add your handling code here:
 // Vérifier que les dates sont bien sélectionnées
    if (date_debut.getDate() == null || date_fin.getDate() == null) {
        Methodes.showInfo("Veuillez sélectionner les deux dates.");
        return;
    }

    // Récupérer les dates depuis les JDateChooser
    java.util.Date utilDateDebut = date_debut.getDate();
    java.util.Date utilDateFin = date_fin.getDate();

    try {
        Connection conn = Methodes.getconnexion();
        if (conn == null) return;

        Entre entre = new Entre(conn);
        List<Map<String, Object>> data = entre.rechercherParDates(utilDateDebut, utilDateFin);

        if (data.isEmpty()) {
            Methodes.showInfo("Aucun mouvement trouvé entre ces deux dates.");
            return;
        }

        // Colonnes à afficher dans le tableau
        Map<String, String> titres = Map.of(
            "dateEntre", "Date d’entrée",
            "motif", "Motif",
            "montantEntre", "Montant"
        );

        DefaultTableModel model = Methodes.createTableModel(data, titres);
        tableEntres.setModel(model); // Remplir ton JTable

    } catch (SQLException e) {
        Methodes.showError("Erreur lors de la recherche : " + e.getMessage());
    }

    }//GEN-LAST:event_btnmovcaisseentreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EntreView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PannelAjouteEntre;
    private javax.swing.JButton btnmovcaisseentre;
    private javax.swing.JButton btnrecherche;
    private com.toedter.calendar.JDateChooser date_debut;
    private com.toedter.calendar.JDateChooser date_fin;
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private java.awt.Label label1;
    private javax.swing.JTable tableEntres;
    private javax.swing.JTextField txtrecherche;
    // End of variables declaration//GEN-END:variables
}
