
package caiseeglise;

import caiseeglise.Models.Methodes;
import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.JPanel;


public class Histograminfo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Histograminfo.class.getName());

    /**
     * Creates new form Histograminfo
     */
    public Histograminfo() {
        initComponents();
        
         // Attend que la fenêtre soit visible pour afficher correctement
    
        appel_affiche();
    
          //classe eglise
        Style style = new Style();
      
       
        style.styliserBoutonPrimary(btngenerehisto);
          
            
            
                style.styliserTextField(txtideglise);
                
                style.styliserTextField(txtmois);
        
   
    }
     //apppel de la fonction get pane
         public JPanel getPannelHisto() {
        return this.PanleHisto;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanleHisto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtideglise = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtmois = new javax.swing.JTextField();
        btngenerehisto = new javax.swing.JButton();
        PanelHisto = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("id eglise");

        jLabel2.setText("mois");

        btngenerehisto.setText("genere");
        btngenerehisto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngenerehistoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelHistoLayout = new javax.swing.GroupLayout(PanelHisto);
        PanelHisto.setLayout(PanelHistoLayout);
        PanelHistoLayout.setHorizontalGroup(
            PanelHistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 892, Short.MAX_VALUE)
        );
        PanelHistoLayout.setVerticalGroup(
            PanelHistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanleHistoLayout = new javax.swing.GroupLayout(PanleHisto);
        PanleHisto.setLayout(PanleHistoLayout);
        PanleHistoLayout.setHorizontalGroup(
            PanleHistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanleHistoLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(PanleHistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanleHistoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(58, 58, 58)
                        .addComponent(txtmois))
                    .addGroup(PanleHistoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(41, 41, 41)
                        .addComponent(txtideglise, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53)
                .addComponent(btngenerehisto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanleHistoLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(PanelHisto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanleHistoLayout.setVerticalGroup(
            PanleHistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanleHistoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(PanleHistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtideglise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addGroup(PanleHistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btngenerehisto))
                .addGap(18, 18, 18)
                .addComponent(PanelHisto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(PanleHisto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanleHisto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btngenerehistoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngenerehistoActionPerformed
        // TODO add your handling code here:
       
   String txtideglise = this.txtideglise.getText().trim();
    String txtmoisStr = this.txtmois.getText().trim();

    if (txtideglise.isEmpty()) {
        Methodes.showInfo("Veuillez saisir l'ID de l'église.");
        return;
    }

    int mois;
    try {
        mois = Integer.parseInt(txtmoisStr);
        if (mois < 1 || mois > 12) {
            Methodes.showInfo("Veuillez saisir un numéro de mois valide (1-12).");
            return;
        }
    } catch (NumberFormatException e) {
        Methodes.showInfo("Le mois doit être un nombre entre 1 et 12.");
        return;
    }

    PanelHisto.removeAll();
    PanelHisto.setLayout(new BorderLayout());
    
//  mise en place d'apple

    HistogrammeCaisse histogramme = new HistogrammeCaisse(txtideglise, mois);

    histogramme.setPreferredSize(PanelHisto.getSize()); // Ajuste la taille au parent
    PanelHisto.add(histogramme, BorderLayout.CENTER);

    PanelHisto.revalidate();
    PanelHisto.repaint();
    }//GEN-LAST:event_btngenerehistoActionPerformed

     public void appel_affiche() {
        // Vérifie que le panel a une taille correcte (parfois non dispo à l'init)
        if (PanelHisto == null || PanelHisto.getWidth() == 0) {
            System.out.println("PanelHisto n'est pas encore prêt !");
            return;
        }

        HistogrammeCaisse histogramme = new HistogrammeCaisse("EG001", 7);
        histogramme.setPreferredSize(PanelHisto.getSize()); 
        PanelHisto.setLayout(new BorderLayout());
        PanelHisto.removeAll(); // Vide l'ancien contenu

        PanelHisto.add(histogramme, BorderLayout.CENTER);
        PanelHisto.revalidate();
        PanelHisto.repaint();
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Histograminfo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelHisto;
    private javax.swing.JPanel PanleHisto;
    private javax.swing.JButton btngenerehisto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtideglise;
    private javax.swing.JTextField txtmois;
    // End of variables declaration//GEN-END:variables
}
