
package caiseeglise;

import caiseeglise.Models.Sortie;
import caiseeglise.Models.Methodes;
import caiseeglise.SortieForm.SortieAjouter;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import java.util.Map;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


public class SortieView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SortieView.class.getName());

    /**
     * Creates new form SortieView
     */
    public SortieView() {
        initComponents();
        //appel de la fonction affiche
        affiche_Sortie();
        
         Style style = new Style();
        style.appliquerStyleTableau(TableSortie);
        style.appliquerStyleH1(label1);
        style.styliserBoutonPrimary(btnajouteSortie);
        
        
        
        
        
         
    }
public JPanel getPanelSortie() {
        return this.PanleSortie;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanleSortie = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        btnajouteSortie = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableSortie = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setText("PAGE SORTIE");

        btnajouteSortie.setText("Ajouter");
        btnajouteSortie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnajouteSortieActionPerformed(evt);
            }
        });

        TableSortie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TableSortie);

        javax.swing.GroupLayout PanleSortieLayout = new javax.swing.GroupLayout(PanleSortie);
        PanleSortie.setLayout(PanleSortieLayout);
        PanleSortieLayout.setHorizontalGroup(
            PanleSortieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanleSortieLayout.createSequentialGroup()
                .addGroup(PanleSortieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanleSortieLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152)
                        .addComponent(btnajouteSortie, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanleSortieLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 931, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        PanleSortieLayout.setVerticalGroup(
            PanleSortieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanleSortieLayout.createSequentialGroup()
                .addGroup(PanleSortieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanleSortieLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanleSortieLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnajouteSortie, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(PanleSortie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanleSortie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnajouteSortieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajouteSortieActionPerformed
        // TODO add your handling code here:
        
          SortieAjouter Sortie = new SortieAjouter();
        Sortie.setLocationRelativeTo(null);
        Sortie.setVisible(true);
    }//GEN-LAST:event_btnajouteSortieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SortieView().setVisible(true));
    }
    
    public void affiche_Sortie(){
         try {
        Connection conn = Methodes.getconnexion();
        if (conn == null) return;

        Sortie sortie = new Sortie(conn);
        List<Map<String, Object>> data = sortie.afficheSorties();

        Map<String, String> titres = Map.of(
            "idsortie", "ID",
            "motif", "Motif",
            "montantSortie", "Montant",
            "dateSortie", "Date",
            "ideglise", "ID Église"
        );

        DefaultTableModel model = Methodes.createTableModel(data, titres);
        TableSortie.setModel(model); // ton JTable

    } catch (SQLException e) {
        Methodes.show("Erreur lors de l'affichage : " + e.getMessage());
    }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanleSortie;
    private javax.swing.JTable TableSortie;
    private javax.swing.JButton btnajouteSortie;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
